# Some tips for how to use loops in Python

In [1]:
import numpy as np

In [2]:
# Example where the loop variable is an index.
#
# For many of the finite difference problems in this course, this will be the preferred way to write loops since 
# you get the index i explicitly


# Create an array of 11 floating point numbers:
n = 11
time = np.linspace(0,10,n)

# A loop that prints them out:
for i in range(0,n):
    print("i = ",i," time = ",time[i])
    
# Note than range(0,n) generates a list of integers from 0 up to but not including n. 
# So "for i in range(0,n)" loops over the values in that range.

i =  0  time =  0.0
i =  1  time =  1.0
i =  2  time =  2.0
i =  3  time =  3.0
i =  4  time =  4.0
i =  5  time =  5.0
i =  6  time =  6.0
i =  7  time =  7.0
i =  8  time =  8.0
i =  9  time =  9.0
i =  10  time =  10.0


In [3]:
# Looping through values in an array without using an index:
time = np.linspace(0,10,11)

for t in time:   # this takes the values of t directly out of the array time. Note that t is a value NOT an index
    print(t)  

# For many of the finite difference problems in our course, this is NOT the way to write your loops!    

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [4]:
# A simple while loop. The loop stops when count == 10
count = 0
while count < 10:
    count += 1  # this is the same as "count = count + 1"
    print(count)

1
2
3
4
5
6
7
8
9
10


In [5]:
# Similar to the above loop, but this one prints out the value every 10 loop iterations:
count = 0
while count < 100:
    count += 1  # this is the same as "count = count + 1"
    
    if np.mod(count,10) == 0:   #  np.mod(a,b) == 0 when the remainder of a/b is zero. 
        print(count)

10
20
30
40
50
60
70
80
90
100


# Tip for using logical indices to work on subsets of an array:

In [6]:
# Create an array:
h = np.array([0.1, 0.2, 0, 1.2, 0, 0, 8.9, 4.2])

# now suppose we want to create an array u = 1/h. This will blow up for any 0 values in h, so 
# we should only compute u where h has non-zero value.

u = np.zeros_like(h) # creates a zeros array the same size as h

# Method 1 (not recommended but it works)
for i in range(0,len(u)):
    if h[i] != 0:            # "!=" is the "not equal to" operator.
        u[i] = 1.0/h[i]

# Method 2 (RECOMMENDED WAY)
nonzero = h != 0              # nonzero is a logical array of same dimension as h.
u[nonzero] = 1./h[nonzero]   # everywhere nonzero = true, u gets updated to be 1/h.

# or you could do this:
# u[h!=0] = 1./h[h!=0]



In [7]:
print(h)
print(nonzero)


[ 0.1  0.2  0.   1.2  0.   0.   8.9  4.2]
[ True  True False  True False False  True  True]


# Appending and inserting values into an existing array
np.append() and np.insert()

In [11]:
a = np.array([1,2,3])

# append values to the END of an array:
a = np.append(a,4)
print(a)
a = np.append(a,[5,6,7])
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7]


In [18]:
a = np.array([2,3,4])

# np.insert(array,index,values) inserts [values] starting at the index. 
# note that this inserts the values into the array, making it longer. 

# Insert value index 0. 
a = np.insert(a,0,[0,1])
print(a)

# Insert some values in the middle of the array:
a = np.array([0,1,2,3,4])
a = np.insert(a,3,[11,12,13])
print(a)

[0 1 2 3 4]
[ 0  1  2 11 12 13  3  4]
